### ISSUE TITLE
The connection to Dreamscreen is very flaky

### ISSUE THREAD

**Issue by prateek33** [legioner0/dreamscreen-btle#2]
The connection to Dreamscreen in very flaky. Sometimes it connects and sometimes it fails to connect. I have the address hardcoded after I verified and I skip the discovery part to make it faster but conn = btle.Peripheral(dev.addr) will sometime connect but mostly throws fails to connect.

**Comment by legioner0** [comment]
I know, but this it the problem in DS, not in python interface. You can see discussion about this problem on DS forum - http://dreamscreen.boards.net/thread/14/bluetooth-connection-weak-disrupted

**Comment by prateek33** [comment]
Yeah.. seems like a lot of people are facing the same issue. I even moved my rpi next the dreamscreen stick but it is still unreliable. Is it possible to keep a connection alive? I have a web server running on rpi which acts like a wifi bridge to the dreamscreen. Can I make the connection once and keep it alive? Or does BLE connection time out after a while?

**Comment by legioner0** [comment]
I don't know, I've not testing long time connection.
Anyway your controlling program must have implementation of reconnection after disconnect.

**Comment by prateek33** [comment]
no problem. Yes I have a reconnection mechanism which is basically creating a new Peripheral object since the old peripheral object can't be reused after disconnect (according to bluepy doc)
